maximum_email_length: 255
maximum_name_length: 50
maximum_post_length: 140
minimum_password_length: 6
ava_size: 80
m_ava_size: 50
remember_yes: "1"
per_page: 15
standard_memory: 5
Settings.px_size: 400
